CREATE TABLE "USERS" (
	"USER_NO"	NUMBER		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"LOGIN_TYPE"	VARCHAR2(20)		NOT NULL,
	"PASSWORD"	VARCHAR2(150)		NULL,
	"PHONE"	VARCHAR2(100)		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"ROLE"	VARCHAR2(20)	DEFAULT 'B'	NULL,
	"USER_NAME"	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "USERS"."USER_NO" IS 'PRIMARYKEY(시퀀스)';

COMMENT ON COLUMN "USERS"."LOGIN_TYPE" IS '1.세션로그인, 2. 카카오, 3. 구글, 4. 네이버';

COMMENT ON COLUMN "USERS"."ROLE" IS 'B=> 브론즈, S => 실버, G => 골드';

CREATE TABLE "PROGRAM" (
	"PROGRAM_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"PROGRAM_NAME"	VARCHAR2(20)		NOT NULL,
	"PROGRAM_ACTIVITY_START_DATE"	DATE		NOT NULL,
	"PROGRAM_ACTIVITY_END_DATE"	DATE		NOT NULL,
	"ACTIVITY_TYPE"	VARCHAR2(1)		NOT NULL,
	"ACTIVITY_TIME"	VARCHAR2(1)		NOT NULL,
	"ACTIVITY_DAYS"	VARCHAR2(1)		NOT NULL,
	"ACTIVITY_LOCATION"	VARCHAR2(20)		NULL,
	"PROGRAM_CAPACITY"	NUMBER		NULL,
	"PROGRAM_ENROLL_END_DATE"	DATE		NULL,
	"PROGRAM_CONTENT"	VARCHAR2(400)		NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "PROGRAM"."ACTIVITY_TYPE" IS 'R:정기 / T:일시';

COMMENT ON COLUMN "PROGRAM"."ACTIVITY_TIME" IS 'A:오전, P:오후, E:저녁';

COMMENT ON COLUMN "PROGRAM"."ACTIVITY_DAYS" IS '1:월';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(20)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(400)		NOT NULL,
	"COUNT"	NUMBER		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL
);

CREATE TABLE "DONATE_INFO" (
	"PAY_NO"	NUMBER		NOT NULL,
	"PAY_TYPE"	VARCHAR2(1)	DEFAULT C	NOT NULL,
	"BANK"	NUMBER		NULL,
	"ACCOUNT"	NUMBER		NULL,
	"DONATE_INFO_NO"	NUMBER		NULL,
	"DONATE_AMOUNT"	NUMBER	DEFAULT 10000	NOT NULL,
	"OPTIONAL_TEXT"	VARCHAR2(4000)		NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"DONATE_NO"	NUMBER		NOT NULL,
	"BILL_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "DONATE_INFO"."PAY_TYPE" IS 'C:신용카드 / A:자동이체';

CREATE TABLE "BOARD_TYPE" (
	"BOARD_TYPE_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NAME"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_TYPE_NAME" IS 'C:커뮤니티 / N:공지사항 /Q: 자주묻는 질문/ R : 후기';

CREATE TABLE "ATTACHMENT" (
	"FILE_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(200 BYTE)		NULL,
	"CHANGE_NAME"	VARCHAR2(200 BYTE)		NULL,
	"FILE_PATH"	VARCHAR2(4000)		NOT NULL,
	"REF_FNO"	VARCHAR2(200 BYTE)		NULL,
	"FILE_TYPE"	VARCHAR2(1 BYTE)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT Y	NULL,
	"IMG_LEVEL"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "ATTACHMENT"."FILE_NO" IS '파일번호';

COMMENT ON COLUMN "ATTACHMENT"."REF_FNO" IS 'v';

COMMENT ON COLUMN "ATTACHMENT"."FILE_TYPE" IS 'P:프로그램 / D:후원금게시글 / B : 게시글 / P : 물품기부';

COMMENT ON COLUMN "ATTACHMENT"."IMG_LEVEL" IS '0부터 시작';

CREATE TABLE "LIKE" (
	"PROGRAM_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL
);

CREATE TABLE "CHAT" (
	"CHAT_NO"	NUMBER		NOT NULL,
	"CHAT_TITLE"	VARCHAR2		NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"USER_NO"	NUMBER		NOT NULL
);

CREATE TABLE "CHAT_MESSAGE" (
	"CM_NO"	NUMBER		NOT NULL,
	"MESSAGE"	VARCHAR2(4000)		NULL,
	"CREATE_DATE"	DATE		NOT NULL,
	"CHAT_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL
);

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"REPORT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"REPLY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPLY_NO" IS '시퀀스';

CREATE TABLE "DONATE_PRODUCT" (
	"PRODUCT_NO"	NUMBER		NOT NULL,
	"PRODUCT_TYPE"	VARCHAR2(1)		NOT NULL,
	"PUSER_NAME"	VARCHAR2		NOT NULL,
	"BUSINESS_NAME"	VARCHAR2		NULL,
	"PHONE"	VARCHAR2		NOT NULL,
	"EMAIL"	VARCHAR2		NOT NULL,
	"PRODUCT_WAY"	VARCHAR2(1)		NOT NULL,
	"PRODUCT_AMOUNT"	NUMBER		NOT NULL,
	"RECEIPT"	VARCHAR2(1)	DEFAULT N	NOT NULL,
	"BUSINESS_NUM"	VARCHAR2		NULL,
	"RESIDENT_NUM"	VARCHAR2		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	"PRODUCT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "DONATE_PRODUCT"."PRODUCT_TYPE" IS 'B:기업/G:개인';

COMMENT ON COLUMN "DONATE_PRODUCT"."PRODUCT_WAY" IS 'V:방문/P:택배';

COMMENT ON COLUMN "DONATE_PRODUCT"."RECEIPT" IS 'N:미발급 / Y:발급';

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '시퀀스';

CREATE TABLE "DONATE_BOARD" (
	"DONATE_NO"	NUMBER		NOT NULL,
	"DONATE_TITLE"	VARCHAR2		NOT NULL,
	"DONATE_CONTENT"	VARCHAR2		NOT NULL,
	"DONATE_HOPE"	NUMBER		NOT NULL,
	"DONATE_START_DATE"	DATE		NULL,
	"DONATE_END_DATE"	DATE		NULL,
	"DONATE_FOUNDATION"	VARCHAR2		NOT NULL,
	"COUNT"	NUMBER	DEFAULT 0	NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);

CREATE TABLE "CHAT_JOIN" (
	"USER_NO"	NUMBER		NOT NULL,
	"CHAT_NO"	NUMBER		NOT NULL
);

CREATE TABLE "REQUEST" (
	"REQUEST_NO"	NUMBER		NOT NULL,
	"REQUEST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"PROGRAM_NO"	NUMBER		NOT NULL
);

CREATE TABLE "PRODUCT_CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(1000)		NOT NULL
);

ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "PROGRAM" ADD CONSTRAINT "PK_PROGRAM" PRIMARY KEY (
	"PROGRAM_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "DONATE_INFO" ADD CONSTRAINT "PK_DONATE_INFO" PRIMARY KEY (
	"PAY_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_TYPE_NO"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "PK_ATTACHMENT" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "PK_CHAT" PRIMARY KEY (
	"CHAT_NO"
);

ALTER TABLE "CHAT_MESSAGE" ADD CONSTRAINT "PK_CHAT_MESSAGE" PRIMARY KEY (
	"CM_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "DONATE_PRODUCT" ADD CONSTRAINT "PK_DONATE_PRODUCT" PRIMARY KEY (
	"PRODUCT_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "DONATE_BOARD" ADD CONSTRAINT "PK_DONATE_BOARD" PRIMARY KEY (
	"DONATE_NO"
);

ALTER TABLE "CHAT_JOIN" ADD CONSTRAINT "PK_CHAT_JOIN" PRIMARY KEY (
	"USER_NO",
	"CHAT_NO"
);

ALTER TABLE "REQUEST" ADD CONSTRAINT "PK_REQUEST" PRIMARY KEY (
	"REQUEST_NO"
);

ALTER TABLE "PRODUCT_CATEGORY" ADD CONSTRAINT "PK_PRODUCT_CATEGORY" PRIMARY KEY (
	"CATEGORY_NO"
);

